export const projects = [
  {
    name: "Weaves of Maheshwar",
    client: "People’s Archive of Rural India",
    category: "Craft",
    link: "https://youtu.be/f_t1mHjxaNw",
    logline: `‘Weaves of Maheshwar’, a National Award–winning triumph, ignites a historic handloom revival through its fierce human guardians.`,
    cover: "",
  },
  {
    name: "To Turn a Tide",
    client: "The Nudge Institute",
    category: "Environmental",
    link: "https://www.youtube.com/watch?v=8J59WBTqX6U",
    logline: `"To Turn a Tide" tracks defiant farmers and grassroots innovators battling back with clever water hacks, unbreakable grit, and united resolve.`,
    cover: "",
  },
  {
    name: "Madhubani",
    client: "",
    category: "Craft",
    link: "https://youtu.be/XO7KPnENbf4",
    logline: `Madhubani art masquerades as mere decorative strokes on fabric and canvas.Yet it throbs with a fierce lineage—stories, beliefs, and heritage fused into the pulse of lived experience.`,
    cover: "",
  },
  {
    name: "Rahul Mishra: Kimkhab",
    client: "",
    category: "Fashion",
    link: "https://youtu.be/QnsYhcsk7tk",
    logline: `'Kamkhab' unfolds as a garland of dreams—where memory, emotion, and imagination merge, echoing the hand-painted frescos of a family home and the intimate artistry that binds dreams to reality.`,
    cover: "",
  },
  {
    name: "The Dawn, Spring 2021 Collection",
    client: "Rahul Mishra",
    category: "Fashion",
    link: "https://youtu.be/fPFUAYUP7hw",
    logline: `A retrieval of colour to a world drained of its natural resources, abundance and animation through years of piling marble dust.`,
    cover: "",
  },
  {
    name: "Indigo - Blue of the Earth",
    client: "Rahul Mishra",
    category: "Craft",
    link: "https://youtu.be/0nAdT7tdpxc",
    logline: `Forged from the Indigofera plant and centuries of ancestral wisdom, natural Indigo dyes whisper a saga of sustainable craft and profound human-nature bonds.`,
    cover: "",
  },
  {
    name: "Telepathic Communication",
    client: "Earthwise",
    category: "Environmental",
    link: "https://www.youtube.com/watch?v=s1eFNaZhLCA&t=105s",
    logline: `In warm conversation with Manjiri Latey, the film opens a vivid space of telepathic connection—felt deeply, seen clearly, and understood with quiet wonder.`,
    cover: "",
  },
  {
    name: "Take a Look",
    client: "Laffaire",
    category: "Fiction",
    link: "https://www.youtube.com/watch?v=r9Mf9-GfPXI",
    logline: `In a throwaway world of disposable clothing, the film rips open fast fashion's dirty secret—its ruthless toll on our planet. It demands we wake up and choose conscious style with fierce urgency.`,
    cover: "",
  },
  {
    name: "Meri Dastaan",
    client: "Krishna Pran Breast Cancer Care Trust",
    category: "Fiction",
    link: "https://www.youtube.com/watch?v=t3XMF8hbUMo",
    logline: `'Meri Dastan' is a story of courage and resilience, following an individual’s journey through breast cancer to affirm that with awareness, hope, and support, the disease is treatable.`,
    cover: "",
  },
  {
    name: "The Kitchen Garden",
    client: "Happy Patterns",
    category: "Brand Story",
    link: "https://www.instagram.com/tv/Cam9BeWA09O/",
    logline: `Shivranjani's Happy Patterns spraks 'Kitchen Garden'—art that transforms humble vegetables into vibrant emblems of beauty, creativity, and tender care. This joyful fusion celebrates life's simple abundance .`,
    cover: "",
  },
  {
    name: "Tholubomalatta",
    client: "Sarmaya Arts Foundation",
    category: "Craft",
    link: "https://youtu.be/fsDX54jB--4",
    logline: `Paul's fateful meeting with Tholubommalata master artisan Mr. Chidambara Rao sparks an explosive bond, a defiant stand against India's vanishing handicraft legacy.`,
    cover: "",
  },
  {
    name: "An Ode to Daabu",
    client: "Aavran",
    category: "Craft",
    link: "https://youtu.be/0fFR-jNjB80",
    logline: `Rooted in Rajasthan's ancient Daabu printing legacy, the film trails Udaipur's Avrana brand as it resurrects indigo-dyed, handcrafted textiles for today's world.`,
    cover: "",
  },
  {
    name: "Chandrani - The Pasra Weaver",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=a7qs-5DmexE",
    logline: `In the Crafting Futures India Project residency by British Council, Chandrani—a gifted Agartala weaver in Tripura—transforms ancestral threads into self-employment gold.`,
    cover: "",
  },
  {
    name: "The Benaras Project",
    client: "Mastani",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=AX3FC5rNzxw",
    logline: `From raw thread's humble birth to vibrant Banaras fabric glory, artisans dye brilliant yarns, painstakingly craft Jacquard cards, and sketch intricate graphs.`,
    cover: "",
  },
  {
    name: "Weaving - The Lost Tradition",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=J5a6q4bi6cA",
    logline: `Rupinis, Tripura's ancient tribal weavers, defy fading traditions by handcrafting Risa and Pasra garments from organic cotton and nature's dyes.`,
    cover: "",
  },
  {
    name: "Pardita - Weaving Threads Through Tradition",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=zeNkCLWORdE",
    logline: `Pardita, incharge and MD of Shankhala Handloom Cluster in Simna, ignites women's independence through ancestral weaving skills turned income lifeline.`,
    cover: "",
  },
  {
    name: "Shondha - Giving Flight to Dreams",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=bsjk09qEPRk",
    logline: `Shondha Debbarma, fierce leader of Tripura Adibashi Mahila Samiti's Self Help Group, battles with unyielding grit for her tribal sisters.`,
    cover: "",
  },
  {
    name: "Risa - The Sacred Cloth",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=xYe_DDzY6kk",
    logline: `the Debbarma community reveres Lakshmi as Mailuma,The sacred Risa, draped in grace and strength, weaves through rituals and festivals as a timeless emblem of their enduring traditions.`,
    cover: "",
  },
  {
    name: "Pehchaan - The Discerning Eye",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/ck25bSSnwFU",
    logline: `‘Pehchaan’ unveils sustainable luxury as Anita Lal crafts a timeless quilt, where discerning eyes meet responsible hands.`,
    cover: "",
  },
  {
    name: "The Patola Poems of Patan",
    client: "Laffaire",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=YvK2Dr011vk",
    logline: `Born from months of grueling precision, the Patan Patola saree stands as a double ikat masterpiece—where flawless dye alignment meets superhuman skill.`,
    cover: "",
  },
  {
    name: "Upada - Jamdani of Andhra",
    client: "Laffaire",
    category: "Craft",
    link: "https://youtu.be/dPStb218w3E",
    logline: `The film unveils Jamdani's ancient handloom sorcery—delicate motifs woven thread by excruciating thread.`,
    cover: "",
  },
  {
    name: "Bandhani - Knots of Tradition",
    client: "Laffaire",
    category: "Craft",
    link: "https://youtu.be/UlmSUqFjNJg",
    logline: `From a single tied dot exploding into thousands of patterns, the film trails Kutch’s Khatri artisans wielding Bandhini’s magic.`,
    cover: "",
  },
  {
    name: "Muqaish - Metallic Embroidery",
    client: "Laffaire",
    category: "Craft",
    link: "https://youtu.be/dUT0rHiBrEI",
    logline: `The film ignites Muqaish embroidery's royal fire—from Lucknow's opulent courts to today's brink of oblivion.`,
    cover: "",
  },
  {
    name: "Story of Kansa",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/NampOBzDIDg",
    logline: `Rooted in Ayurvedic wisdom, the film unveils Kansa serviceware—handcrafted by tribal artisans and revered across generations.`,
    cover: "",
  },
  {
    name: "Chintz of Coromandel Coast",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/FcPy613gjJ8",
    logline: `Once Europe's fashion wildfire, Coromandel Coast Chintz now flickers near extinction—its Machilipatnam cradle guarding a faded global empire.`,
    cover: "",
  },
  {
    name: "Gyasar Weave",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/fH9D2Lqg0yU",
    logline: `‘The Gyasar Weave’ unveils sustainable luxury's soul—where bold original design fuses with masterful Banaras handloom craft and profound material wisdom.`,
    cover: "",
  },
  {
    name: "Naqashi",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/18S9jHq50EA",
    logline: `‘The film’ ignites Kashmiri Naqashi's timeless fire through Good Earth’s Nigeen Papier Mâché Bowls.`,
    cover: "",
  },
  {
    name: "Namda",
    client: "Anantaya",
    category: "Craft",
    link: "https://youtu.be/2Uzipl1ztFI",
    logline: `Namda rugs from Rajasthan echo Kashmir's ancient felted wool tradition—raw sheep fibers beaten, soaped, and pressed into loom-free, resilient masterpieces without weaving.`,
    cover: "",
  },
  {
    name: "Thathera",
    client: "Anantaya",
    category: "Craft",
    link: "https://youtu.be/NPgozdYYxtg",
    logline: `Thathera artisans of Rajasthan forge divine brassware from hammered sheets—punching intricate motifs in a sacred craft born from temple rituals and royal courts.`,
    cover: "",
  },
  {
    name: "Sand Casting",
    client: "Anantaya",
    category: "Craft",
    link: "https://youtu.be/QM2UFC3JiAg",
    logline: `Rajasthan's sand casting artisans pack desert sands into molds, pouring molten metal to birth intricate brass icons and vessels from ancient rituals.`,
    cover: "",
  },
  {
    name: "Tazia",
    client: "Anantaya",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=1rliW_wE2iM",
    logline: `Rajasthan's Tazia artisans craft ornate paper-and-bamboo replicas of Imam Hussain's shrine—towering symbols of Muharram devotion, gilded with love and communal harmony.`,
    cover: "",
  },
];
