const filmsData = [
  {
    name: "Block Printing",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/dBNivbpSERQ",
    category: "craft",
  },
  {
    name: "Namda",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/2Uzipl1ztFI",
    category: "craft",
  },
  {
    name: "Thathera",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/NPgozdYYxtg",
    category: "craft",
  },
  {
    name: "Panja Durrie",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/Xk1rY7jba-I",
    category: "craft",
  },
  {
    name: "Sand casting",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/QM2UFC3JiAg",
    category: "craft",
  },
  {
    name: "Tazia",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/1rliW_wE2iM",
    category: "craft",
  },
  {
    name: "Stone Craving",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/aW5_cBTPlgI",
    category: "craft",
  },
  {
    name: "Varakh",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/Y0onCb5HyVg",
    category: "craft",
  },
  {
    name: "Sultana",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/78t41NERYV0",
    category: "craft",
  },
  {
    name: "Introducing Anantaya",
    year: "2013-14",
    client: "Anantaya Decore",
    director: "Keya and Nidhi",
    link: "https://youtu.be/QeZJpyDgkg4",
    category: "craft",
  },
  {
    name: "Cognus Corporate Film",
    year: "2013-14",
    client: "Cognus",
    director: "Keya and Nidhi",
    link: "https://www.youtube.com/watch?v=JvR4IQFulPA",
    category: "Corporate",
  },
  {
    name: "Pehchaan - The Discerning Eye",
    year: "2014-22",
    client: "Good Earth",
    director: "Keya and Nidhi",
    link: "https://youtu.be/ck25bSSnwFU",
    category: "craft",
  },
  {
    name: "Story of Kansa",
    year: "2014-22",
    client: "Good Earth",
    director: "Keya and Nidhi",
    link: "https://youtu.be/NampOBzDIDg",
    category: "craft",
  },
  {
    name: "Chintz of Coromandel Coast",
    year: "2014-22",
    client: "Good Earth",
    director: "Keya and Nidhi",
    link: "https://youtu.be/FcPy613gjJ8",
    category: "craft",
  },
  {
    name: "Gyasar Weave",
    year: "2014-22",
    client: "Good Earth",
    director: "Keya and Nidhi",
    link: "https://youtu.be/fH9D2Lqg0yU",
    category: "craft",
  },
  {
    name: "Naqashi",
    year: "2014-22",
    client: "Good Earth",
    director: "Keya and Nidhi",
    link: "https://youtu.be/18S9jHq50EA",
    category: "craft",
  },
  {
    name: "Design Story",
    year: "2014-22",
    client: "Good Earth",
    director: "Nidhi",
    link: "https://youtu.be/ymmfuIgMQHE",
    category: "craft",
  },
  {
    name: "The Patola Poems of Patan",
    year: "2016-19",
    client: "Laffaire",
    director: "Keya and Nidhi",
    link: "https://www.youtube.com/watch?v=YvK2Dr011vk&t=2s",
    category: "craft",
  },
  {
    name: "Upada - Jamdani of Andhra",
    year: "2016-19",
    client: "Laffaire",
    director: "Keya and Nidhi",
    link: "https://youtu.be/dPStb218w3E",
    category: "craft",
  },
  {
    name: "Bandhani - Knots of Tradition",
    year: "2016-19",
    client: "Laffaire",
    director: "Keya and Nidhi",
    link: "https://youtu.be/UlmSUqFjNJg",
    category: "craft",
  },
  {
    name: "Muqaish - Metallic Embroidery",
    year: "2016-19",
    client: "Laffaire",
    director: "Keya and Nidhi",
    link: "https://youtu.be/dUT0rHiBrEI",
    category: "craft",
  },
  {
    name: "Indigo - Blue of the Earth",
    year: "2016-19",
    client: "Laffaire",
    director: "Keya",
    link: "https://youtu.be/0nAdT7tdpxc",
    category: "craft",
  },
  {
    name: "Weaves of Maheshwar",
    year: "2016-17",
    client: "People’s Archive of Rural India",
    director: "Keya and Nidhi",
    link: "https://youtu.be/f_t1mHjxaNw",
    category: "craft",
  },
  {
    name: "Khazana",
    year: "2016-17",
    client: "Butterfly NGO | CDC Delhi",
    director: "Keya and Nidhi",
    link: "https://vimeo.com/102298702",
    category: "craft",
  },
  {
    name: "Bodhi",
    year: "2016-17",
    client: "Bodhi",
    director: "Keya and Nidhi",
    link: "https://youtu.be/KL5_qFj7AxE",
    category: "craft",
  },
  {
    name: "Stone Processing",
    year: "2016-17",
    client: "Tab India",
    director: "Keya and Nidhi",
    link: "https://youtu.be/AT9jcQ77cFw",
    category: "craft",
  },
  {
    name: "Wedding Film",
    year: "2016-17",
    client: "Shambhavi & Apoorv",
    director: "Keya and Nidhi",
    link: "https://www.youtube.com/watch?v=s8VY2WsZxKU",
    category: "Wedding Film",
  },
  {
    name: "Meet the work of Ayush",
    year: "2018-19",
    client: "Freedom",
    director: "Keya and Nidhi",
    link: "https://www.youtube.com/watch?v=Cs6FKpA4QcU",
    category: "Brand Story",
  },
  {
    name: "Eodr Design Pvt. Ltd",
    year: "2018-19",
    client: "Eodr Design Pvt. Ltd",
    director: "Keya and Nidhi",
    link: "Only for internal brand use",
    category: "Brand Story",
  },
  {
    name: "An Ode to Daabu",
    year: "2018-19",
    client: "Aavran",
    director: "Keya and Nidhi",
    link: "https://youtu.be/0fFR-jNjB80",
    category: "craft",
  },
  {
    name: "Tholubomalatta",
    year: "2019-20",
    client: "Sarmaya Arts Foundation",
    director: "Keya and Nidhi",
    link: "https://youtu.be/fsDX54jB--4",
    category: "craft",
  },
  {
    name: "Madhubani",
    year: "2019-20",
    client: "Sarmaya Arts Foundation",
    director: "Keya and Nidhi",
    link: "https://youtu.be/XO7KPnENbf4",
    category: "craft",
  },
  {
    name: "Rujuta Shah Design Studio",
    year: "2019-20",
    client: "Rujuta Shah Design Studio",
    director: "Nidhi",
    link: "Only for internal brand use",
    category: "Brand Story",
  },
  {
    name: "Rajkumari Ratnavati School",
    year: "2019-20",
    client: "Conde Nast / Architectural Digest",
    director: "Keya and Nidhi",
    link: "https://youtu.be/PD2XPKFUJnA",
    category: "Architecture",
  },
  {
    name: "Testimonials",
    year: "2019-20",
    client: "Healthyfy Me Wellness Studio",
    director: "Nidhi",
    link: "Only for internal brand use",
    category: "Corporate",
  },
  {
    name: "The Dawn",
    year: "2021-22",
    client: "Rahul Mishra",
    director: "Keya",
    link: "https://youtu.be/fPFUAYUP7hw",
    category: "Fashion",
  },
  {
    name: "Kimkhab",
    year: "2021-22",
    client: "Rahul Mishra",
    director: "Keya",
    link: "https://youtu.be/QnsYhcsk7tk",
    category: "Fashion",
  },
  {
    name: "Andraab, a Collaboration",
    year: "2021-22",
    client: "Andraab",
    director: "Keya",
    link: "Yet to be released",
    category: "Brand Story",
  },
  {
    name: "The Kitchen Garden",
    year: "2021-22",
    client: "Happy Patterns",
    director: "Keya",
    link: "https://www.instagram.com/tv/Cam9BeWA09O/?utm_source=ig_web_copy_link",
    category: "Brand Story",
  },
  {
    name: "Growing Back",
    year: "2021-22",
    client: "Pangaia",
    director: "Keya",
    link: "Not Yet released",
    category: "Enviornmental",
  },
  {
    name: "Telepathic Communication",
    year: "2022",
    client: "Earthwise",
    director: "Keya",
    link: "https://www.youtube.com/watch?v=s1eFNaZhLCA&t=105s",
    category: "Enviornmental",
  },
  {
    name: "Meri Dastaan",
    year: "2023",
    client: "Krishna Pran Breast Cancer Care Trust",
    director: "Keya",
    link: "https://www.youtube.com/watch?v=t3XMF8hbUMo",
    category: "Fiction",
  },
  {
    name: "Take a Look",
    year: "2024",
    client: "Laffaire",
    director: "Keya",
    link: "https://www.youtube.com/watch?v=r9Mf9-GfPXI",
    category: "Fiction",
  },
  {
    name: "To Turn a Tide",
    year: "2025",
    client: "The Nudge Institute",
    director: "Keya",
    link: "https://www.youtube.com/watch?v=8J59WBTqX6U",
    category: "Enviornmental",
  },
];

export { filmsData };
