export const projects = [
  {
    name: "Weaves of Maheshwar",
    client: "People’s Archive of Rural India",
    category: "Craft",
    link: "https://youtu.be/f_t1mHjxaNw",
    logline: `‘Weaves of Maheshwar’, a National Award–winning triumph, ignites a historic handloom revival through its fierce human guardians.`,
    cover: "/project-covers/Weaves of Masheshwar.jpg",
  },
  {
    name: "To Turn a Tide",
    client: "The Nudge Institute",
    category: "Environmental",
    link: "https://www.youtube.com/watch?v=8J59WBTqX6U",
    logline: `To Turn a Tide" tracks defiant farmers and grassroots innovators battling back with clever water hacks, unbreakable grit, and united resolve.`,
    cover: "/project-covers/To turn a tide.jpg",
  },
  {
    name: "Rajkumari Ratnavati School",
    client: "Architectural Digest",
    category: "Architecture",
    link: "https://www.youtube.com/watch?v=PD2XPKFUJnA",
    logline: `In the heart of the Thar Desert, the Rajkumari Ratnavati Girls School stands as a testament to intelligent design—where architecture, climate, and culture converge to shape empowered futures.`,
    cover: "/featured/3.png",
  },
  {
    name: "Madhubani",
    client: "",
    category: "Craft",
    link: "https://youtu.be/XO7KPnENbf4",
    logline: `Madhubani art masquerades as mere decorative strokes on fabric and canvas.Yet it throbs with a fierce lineage—stories, beliefs, and heritage fused into the pulse of lived experience.`,
    cover: "/project-covers/Madhubani.jpg",
  },
  {
    name: "Rahul Mishra: Kimkhab",
    client: "",
    category: "Fashion",
    link: "https://youtu.be/QnsYhcsk7tk",
    logline: `'Kamkhab' unfolds as a garland of dreams—where memory, emotion, and imagination merge, echoing the hand-painted frescos of a family home and the intimate artistry that binds dreams to reality.`,
    cover: "/project-covers/Kim Khab.jpg",
  },
  {
    name: "The Dawn, Spring 2021 Collection",
    client: "Rahul Mishra",
    category: "Fashion",
    link: "https://youtu.be/fPFUAYUP7hw",
    logline: `A retrieval of colour to a world drained of its natural resources, abundance and animation through years of piling marble dust.`,
    cover: "/project-covers/The Dawn.jpg",
  },
  {
    name: "Indigo - Blue of the Earth",
    client: "Rahul Mishra",
    category: "Craft",
    link: "https://youtu.be/0nAdT7tdpxc",
    logline: `Forged from the Indigofera plant and centuries of ancestral wisdom, natural Indigo dyes whisper a saga of sustainable craft and profound human-nature bonds.`,
    cover: "/project-covers/Indigo.jpg",
  },
  {
    name: "A Peek Into Telepathic World",
    client: "Earthwise",
    category: "Environmental",
    link: "https://www.youtube.com/watch?v=s1eFNaZhLCA&t=105s",
    logline: `In warm conversation with Manjiri Latey, the film opens a vivid space of telepathic connection—felt deeply, seen clearly, and understood with quiet wonder.`,
  },
  {
    name: "Take a Look",
    client: "Laffaire",
    category: "Fiction",
    link: "https://www.youtube.com/watch?v=r9Mf9-GfPXI",
    logline: `In a throwaway world of disposable clothing, the film rips open fast fashion's dirty secret—its ruthless toll on our planet. It demands we wake up and choose conscious style with fierce urgency.`,
    cover: "/project-covers/Take a look.jpg",
  },
  {
    name: "Meri Dastaan",
    client: "Krishna Pran Breast Cancer Care Trust",
    category: "Fiction",
    link: "https://www.youtube.com/watch?v=t3XMF8hbUMo",
    logline: `'Meri Dastan' is a story of courage and resilience, following an individual’s journey through breast cancer to affirm that with awareness, hope, and support, the disease is treatable.`,
    cover: "/project-covers/Meri Dastan.jpg",
  },
  {
    name: "The Kitchen Garden",
    client: "Happy Patterns",
    category: "Brand Story",
    link: "https://www.instagram.com/tv/Cam9BeWA09O/",
    logline: `Shivranjani's Happy Patterns spraks 'Kitchen Garden'—art that transforms humble vegetables into vibrant emblems of beauty, creativity, and tender care. This joyful fusion celebrates life's simple abundance .`,
    cover: "/project-covers/The kitchen Garden.jpg",
  },
  {
    name: "Tholubomalatta",
    client: "Sarmaya Arts Foundation",
    category: "Craft",
    link: "https://youtu.be/fsDX54jB--4",
    logline: `Paul's fateful meeting with Tholubommalata master artisan Mr. Chidambara Rao sparks an explosive bond, a defiant stand against India's vanishing handicraft legacy.`,
    cover: "/project-covers/Tholubomalata.jpg",
  },
  {
    name: "An Ode to Daabu",
    client: "Aavran",
    category: "Craft",
    link: "https://youtu.be/0fFR-jNjB80",
    logline: `Rooted in Rajasthan's ancient Daabu printing legacy, the film trails Udaipur's Avrana brand as it resurrects indigo-dyed, handcrafted textiles for today's world.`,
    cover: "/project-covers/Dabu.jpg",
  },
  {
    name: "Chandrani - The Pasra Weaver",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=a7qs-5DmexE",
    logline: `In the Crafting Futures India Project residency by British Council, Chandrani—a gifted Agartala weaver in Tripura—transforms ancestral threads into self-employment gold.`,
    cover: "/project-covers/Chandrani -The Pasra Weaver.jpg",
  },
  {
    name: "The Benaras Project",
    client: "Mastani",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=AX3FC5rNzxw",
    logline: `From raw thread's humble birth to vibrant Banaras fabric glory, artisans dye brilliant yarns, painstakingly craft Jacquard cards, and sketch intricate graphs.`,
    cover: "/project-covers/The Benaras Project.jpg",
  },
  {
    name: "Weaving - The Lost Tradition",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=J5a6q4bi6cA",
    logline: `Rupinis, Tripura's ancient tribal weavers, defy fading traditions by handcrafting Risa and Pasra garments from organic cotton and nature's dyes.`,
    cover: "/project-covers/Weaving - The lost tradition.jpg",
  },
  {
    name: "Pardita - Weaving Threads Through Tradition",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=zeNkCLWORdE",
    logline: `Pardita, incharge and MD of Shankhala Handloom Cluster in Simna, ignites women's independence through ancestral weaving skills turned income lifeline.`,
    cover: "/project-covers/Pardita - Weaving threads through tradition.jpg",
  },
  {
    name: "Shondha - Giving Flight to Dreams",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=bsjk09qEPRk",
    logline: `Shondha Debbarma, fierce leader of Tripura Adibashi Mahila Samiti's Self Help Group, battles with unyielding grit for her tribal sisters.`,
    cover: "/project-covers/Shondha - Giving flight to dreams.jpg",
  },
  {
    name: "Risa - The Sacred Cloth",
    client: "British Council",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=xYe_DDzY6kk",
    logline: `the Debbarma community reveres Lakshmi as Mailuma,The sacred Risa, draped in grace and strength, weaves through rituals and festivals as a timeless emblem of their enduring traditions.`,
    cover: "/project-covers/Risa - The sacred cloth.jpg",
  },
  {
    name: "Pehchaan - The Discerning Eye",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/ck25bSSnwFU",
    logline: `'Pehchaan' unveils sustainable luxury as Anita Lal crafts a timeless quilt, where discerning eyes meet responsible hands.`,
    cover: "/project-covers/Pehchaan block print.jpg",
  },
  {
    name: "The Patola Poems of Patan",
    client: "Laffaire",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=YvK2Dr011vk",
    logline: `Born from months of grueling precision, the Patan Patola saree stands as a double ikat masterpiece—where flawless dye alignment meets superhuman skill.`,
    cover: "/project-covers/The Patola Poems of Patan.jpg",
  },
  {
    name: "Upada - Jamdani of Andhra",
    client: "Laffaire",
    category: "Craft",
    link: "https://youtu.be/dPStb218w3E",
    logline: `The film unveils Jamdani's ancient handloom sorcery—delicate motifs woven thread by excruciating thread.`,
    cover: "/project-covers/Upada - Jamdani of Andhra.jpg",
  },
  {
    name: "Bandhani - Knots of Tradition",
    client: "Laffaire",
    category: "Craft",
    link: "https://youtu.be/UlmSUqFjNJg",
    logline: `From a single tied dot exploding into thousands of patterns, the film trails Kutch’s Khatri artisans wielding Bandhini’s magic.`,
    cover: "/project-covers/Bandhani.jpg",
  },
  {
    name: "Muqaish - Metallic Embroidery",
    client: "Laffaire",
    category: "Craft",
    link: "https://youtu.be/dUT0rHiBrEI",
    logline: `The film ignites Muqaish embroidery's royal fire—from Lucknow's opulent courts to today's brink of oblivion.`,
    cover: "/project-covers/Muqaish - Metallic Embroidery.jpg",
  },
  {
    name: "Story of Kansa",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/NampOBzDIDg",
    logline: `Rooted in Ayurvedic wisdom, the film unveils Kansa serviceware—handcrafted by tribal artisans and revered across generations.`,
    cover: "/project-covers/Story of Kansa.jpg",
  },
  {
    name: "Chintz of Coromandel Coast",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/FcPy613gjJ8",
    logline: `Once Europe's fashion wildfire, Coromandel Coast Chintz now flickers near extinction—its Machilipatnam cradle guarding a faded global empire.`,
    cover: "/project-covers/Chintz of Coromandal Cost.jpg",
  },
  {
    name: "Gyasar Weave",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/fH9D2Lqg0yU",
    logline: `'The Gyasar Weave' unveils sustainable luxury's soul—where bold original design fuses with masterful Banaras handloom craft and profound material wisdom.`,
    cover: "/project-covers/Gyasar Weave.jpg",
  },
  {
    name: "Naqashi",
    client: "Good Earth",
    category: "Craft",
    link: "https://youtu.be/18S9jHq50EA",
    logline: `'The film' ignites Kashmiri Naqashi's timeless fire through Good Earth’s Nigeen Papier Mâché Bowls.`,
    cover: "/project-covers/Naqashi.jpg",
  },
  {
    name: "Namda",
    client: "Anantaya",
    category: "Craft",
    link: "https://youtu.be/2Uzipl1ztFI",
    logline: `Namda rugs from Rajasthan echo Kashmir's ancient felted wool tradition—raw sheep fibers beaten, soaped, and pressed into loom-free, resilient masterpieces without weaving.`,
    cover: "/project-covers/Namda.jpg",
  },
  {
    name: "Thathera",
    client: "Anantaya",
    category: "Craft",
    link: "https://youtu.be/NPgozdYYxtg",
    logline: `Thathera artisans of Rajasthan forge divine brassware from hammered sheets—punching intricate motifs in a sacred craft born from temple rituals and royal courts.`,
    cover: "/project-covers/Thatera.jpg",
  },
  {
    name: "Sand Casting",
    client: "Anantaya",
    category: "Craft",
    link: "https://youtu.be/QM2UFC3JiAg",
    logline: `Rajasthan's sand casting artisans pack desert sands into molds, pouring molten metal to birth intricate brass icons and vessels from ancient rituals.`,
    cover: "/project-covers/Sandcasting.jpg",
  },
  {
    name: "Tazia",
    client: "Anantaya",
    category: "Craft",
    link: "https://www.youtube.com/watch?v=1rliW_wE2iM",
    logline: `Rajasthan's Tazia artisans craft ornate paper-and-bamboo replicas of Imam Hussain's shrine—towering symbols of Muharram devotion, gilded with love and communal harmony.`,
    cover: "/project-covers/Tazia.jpg",
  },
];

export const media = {
  videos: [
    {
      title: "Jungle Bells",
      youtubeId: "z5RbDi2j_pU",
    },
    {
      title: "Her Kahani",
      youtubeId: "He7zFteIOr8",
    },
    {
      title: "The Solopreneurs – Part 1",
      youtubeId: "OCwxv9l6Br4",
    },
    {
      title: "The Solopreneurs – Part 2",
      youtubeId: "zkQ8k4ur9DQ",
    },
    {
      title: "Forbes",
      youtubeId: "lxMJ3o-Ttao",
    },
    {
      title: "TEDx",
      youtubeId: "y1AGQ6SzI0Q",
    },
    {
      title: "AND Academy",
      youtubeId: "EczNb2iMHbw",
    },
  ],

  podcasts: [
    {
      title: "TGL Studios",
      youtubeId: "dDhl-eIsUHE",
    },
    {
      title: "Unraveling Crafts",
      youtubeId: "Y5YPsF2Q1Lc",
    },
  ],

  shorts: [
    {
      youtubeId: "xP6gTEZbzxY",
    },
    {
      youtubeId: "vYlTrwUTZiY",
    },
    {
      youtubeId: "ug375q46TXM",
    },
    {
      youtubeId: "LXEYg0i-9xQ",
    },
  ],

  articles: [
    {
      source: "Forbes",
      title: "Keya Vaswani and Nidhi Kamath weaving their magic on screen",
      link: "https://www.forbesindia.com/article/2019-wpower-trailblazers/keya-vaswani-and-nidhi-kamath-weaving-their-magic-on-screen/52707/1",
    },
    {
      source: "Times of India",
      title: "City filmmaker wins award for film on handloom industry",
      link: "https://timesofindia.indiatimes.com/city/raipur/city-film-maker-wins-award-for-film-on-handloom-industry/articleshow/52338915.cms",
    },
    {
      source: "The Indian Express",
      title: "Retelling India’s textile stories",
      link: "https://www.newindianexpress.com/cities/bengaluru/2016/Jun/19/retelling-indias-textile-stories-941888.html",
    },
    {
      source: "Better India",
      title: "Watch intricate Indian craft unfold",
      link: "https://www.thebetterindia.com/41764/video-watch-see-intricate-indian-craft-unfold-right-front-eyes/",
    },
    {
      source: "Live Mint",
      title: "Weavers in the studio",
      link: "https://www.livemint.com/Leisure/cDZVyPCGl3UOxB0tguUlDJ/Weavers-in-the-studio.html",
    },
    {
      source: "Business Standard",
      title: "Crafted with love",
      link: "https://www.business-standard.com/article/specials/crafted-with-love-116090901266_1.html",
    },
    {
      source: "Verve",
      title: "Behind the lens with Storyloom",
      link: "https://www.vervemagazine.in/tag/behind-the-lens-with-storyloom",
    },
    {
      source: "The News Minute",
      title: "Weaving stories on the loom",
      link: "https://www.thenewsminute.com/features/weaving-stories-loom-how-two-women-are-giving-artisans-voice-through-films-45436",
    },
    {
      source: "News18",
      title:
        "Two women filmmakers are giving Make in India a traditional twist",
      link: "https://www.news18.com/news/buzz/two-women-filmmakers-are-giving-modis-make-in-india-a-traditional-twist-with-their-eye-opening-documentaries-1182758.html",
    },
    {
      source: "The Sindhians",
      title: "Keya Vaswani feature",
      link: "https://www.bindugopalrao.com/the-sindhian-stories-apr-jun-2019/keya-vaswani/",
    },
    {
      source: "Flextiles",
      title: "Jaipur features",
      link: "https://flextiles.wordpress.com/tag/jaipur/",
    },
    {
      source: "Educate Girls",
      title: "Celebrating women trailblazers",
      link: "https://www.educategirls.ngo/blog/celebrating-women-trailblazers-women-who-have-created-their-own-path-and-paved-way-for-others/",
    },
    {
      source: "ARCH College",
      title: "Event feature",
      link: "https://www.archedu.org/events-details.html?event_id=347",
    },
    {
      source: "Young INTACH Explorer",
      title: "Heritage alerts feature",
      link: "https://www.youngintach.org/heritage-alerts-june16",
    },
  ],
};

export const brandLogos = [
  "/brand-logos/1.png",
  "/brand-logos/2.png",
  "/brand-logos/3.png",
  "/brand-logos/4.png",
  "/brand-logos/5.png",
  "/brand-logos/6.png",
  "/brand-logos/7.png",
  "/brand-logos/8.png",
  "/brand-logos/9.png",
  "/brand-logos/10.png",
  "/brand-logos/11.png",
  "/brand-logos/12.png",
  "/brand-logos/13.png",
  "/brand-logos/14.png",
  "/brand-logos/15.png",
  "/brand-logos/16.png",
];

export const featured = [
  {
    title: "To Turn a Tide",
    description:
      "To Turn a Tide tracks defiant farmers and grassroots innovators battling back with clever water hacks, unbreakable grit, and united resolve.",
    image: "/featured/1.png",
    link: "https://www.youtube.com/watch?v=8J59WBTqX6U",
  },
  {
    title: "Weaves of Maheshwar",
    description:
      "Weaves of Maheshwar is a story about craft revival. The documentary revolves around various journeys about people who have made this change possible. In an era where the machines are taking over the world India is the only country which still produces 90% of handloom. Weaves of Maheshwar portrays this strength of Indian textiles and our rich craft sector. The protagonists of this film are a group of people who have facilitated this change.",
    image: "/featured/2.png",
    link: "https://youtu.be/f_t1mHjxaNw",
  },
  {
    title: "Rajkumari Ratnavati School",
    description:
      "In the heart of the Thar Desert, the Rajkumari Ratnavati Girls School stands as a testament to intelligent design—where architecture, climate, and culture converge to shape empowered futures.",
    image: "/featured/3.png",
    link: "https://www.youtube.com/watch?v=PD2XPKFUJnA",
  },
  {
    title: "The Dawn",
    description:
      "A retrieval of colour to a world drained of its natural resources, abundance and animation through years of piling marble dust.",
    image: "/featured/4.png",
    link: "https://youtu.be/fPFUAYUP7hw",
  },
  {
    title: "Tholubomalatta",
    description:
      "Paul's fateful meeting with Tholubommalata master artisan Mr. Chidambara Rao sparks an explosive bond, a defiant stand against India's vanishing handicraft legacy.",
    image: "/featured/5.png",
    link: "https://youtu.be/fsDX54jB--4",
  },
];
